---
- name: Wait for Nodes
  hosts: localhost
  gather_facts: False
  roles:
    - role: infra/wait-for-hosts
      tags: [setup, backup, monitoring]

- hosts: servers
  become_user: root
  any_errors_fatal: "true"
  roles:
    - role: ansible-k3s
      tags: [setup]

    - role: cluster-ctl/cli-install
      tags: [setup]

    - role: cluster-ctl/initialize
      tags: [setup]

    - role: capi-cluster/workload
      tags: [setup]

    - role: capi-cluster/management
      tags: [setup]

    - role: flux-operator
      tags: [setup, flux]

    - role: kube-prometheus
      tags: [setup, monitoring]

    - role: velero
      tags: [setup, backup]