---
- name: Wait for Nodes
  hosts: localhost
  gather_facts: False
  roles:
    - { role: infra/wait-for-hosts }

- hosts: servers
  become_user: root
  any_errors_fatal: "true"
  roles:
    - { role: ansible-k3s }
    - { role: cluster-ctl/cli-install }
    - { role: cluster-ctl/initialize }
    - { role: capi-cluster/workload }
    - { role: capi-cluster/management }