- hosts: localhost
  vars:
    terraform_workspace: default
  tasks:
  - name: Provision infrastructure using Terraform
    terraform:
      project_path: "./terraform"
      state: present
      force_init: yes
      init_reconfigure: yes
      workspace: "{{ terraform_workspace }}"
    register: terraform_provision
    when: (operation == "create")

  - name: Destroy resources
    terraform:
      project_path: "./terraform"
      state: absent
      force_init: yes
      init_reconfigure: yes
      workspace: "{{ terraform_workspace }}"
    when: (operation == "destroy")
    register: destroy
