---
- name: Install K3s with a specific version
  become: true
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" sh -
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s cluster to complete install
  pause:
    seconds: 60

- name: Create .kube directory for root
  become: true
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: Copy K3s kubeconfig to root's kubeconfig
  become: true
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0600'