---
- name: Create Velero backup schedules
  ansible.builtin.shell: >
    velero schedule create {{ item.name }}
    --kubeconfig {{ kubeconfig_path }}
    --schedule="{{ item.schedule }}"
    --namespace velero
    --ttl={{ item.ttl }}
  loop: "{{ velero_backup_schedules }}"

- name: Create initial Velero backup
  ansible.builtin.shell: >
    velero --kubeconfig {{ kubeconfig_path }} \
       backup create initial-capi-backup --ttl=8760h

