---
- name: Check for {{ cluster_name }} calico-kube nodes
  shell: >-
    kubectl --kubeconfig /tmp/{{ cluster_name }}.kubeconfig get pods -A | grep -c calico-kube
  register: calico_kube_pods
  become: true
  ignore_errors: true

- name: Install CNI for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig /tmp/{{ cluster_name }}.kubeconfig apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml
  become: true
  when:
    - calico_kube_pods.stdout != "1"