---
- name: Add GPG apt keys
  apt_key:
    url: "{{ item }}"
    state: present
  become: true
  with_items:
    - https://download.docker.com/linux/ubuntu/gpg

# - name: Add K8s apt keys
#   shell:
#     curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ k8s_bootstrap_version }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  become: true
  with_items:
    - "deb https://download.docker.com/linux/ubuntu focal stable"

- name: Add K8s apt repos
  shell:
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_bootstrap_version }}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Install prerequisite Packages
  apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: true
  become: true

- name: Update apt and install docker-ce
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: true
  become: true

- name: Add docker group to users {{ ansible_user }} groups
  user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker
  become: true

# - name: Install python pre-requisites
#   community.general.pipx:
#     name: "{{ pip_packages }}"
#     state: present
#   become: true