---
kind_git: "https://api.github.com/repos/kubernetes-sigs/kind"
kind_repo: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"

clusterctl_repo: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ clusterctl_version }}/clusterctl-linux-amd64"

required_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - kubectl
  - python3-pip
  - python3-setuptools
  - python3-kubernetes
  - pipx

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

pip_packages:
  - kubernetes