---
velero_tmp_dir: /tmp/velero

velero_version: v1.16.2

velero_tar_url: https://github.com/vmware-tanzu/velero/releases/download/{{ velero_version }}/velero-{{ velero_version }}-linux-amd64.tar.gz

cluster_name: "some-cluster-name"
kubeconfig_path: /tmp/{{ cluster_name }}.kubeconfig

velero_openstack_provider_version: v0.8.0

velero_bucket_name: "kahu-velero-capi-dev"

clouds_yaml_local_location: "/etc/velero/clouds.yaml"

yaml_openstack_cloud: openstack