---
cluster_name: "some-cluster-here"

enable_monitoring: false

tmp_dir: "/tmp/{{ cluster_name }}"
kube_prometheus_version: release-0.14

mimir_endpoint: "someEndPointSomewhere"
loki_endpoint: "someEndPointSomewhere"

monitoring_username: someuser
monitoring_password: supersecretpassword