---
- name: Install Openstack Resource Controller (ORC) CRD's
  shell: >-
    kubectl apply \
    -f https://github.com/k-orc/openstack-resource-controller/releases/download/{{ orc_version }}/install.yaml
  become: true

- name: Initialize the management cluster (Plain)
  shell: >-
    clusterctl init --infrastructure {{ clusterctl_provider }}:{{ clusterctl_provider_version }}
  become: true
  when:
    - capi_deployment != "talos"

- name: Initialize the management cluster (Talos)
  shell: >-
    clusterctl init -c talos -b talos --infrastructure {{ clusterctl_provider }}:{{ clusterctl_provider_version }}
  become: true
  when:
    - capi_deployment == "talos"