---
- name: Initialize | Install Openstack Resource Controller (ORC) CRD's
  shell: >-
    kubectl apply \
    -f https://github.com/k-orc/openstack-resource-controller/releases/download/{{ orc_version }}/install.yaml
  become: true

- name: Initialize | Initialize the management cluster
  shell: >-
    clusterctl init --infrastructure {{ clusterctl_provider }}:{{ clusterctl_provider_version }}
  become: true